import Head from 'next/head'
import HomePage from '../pages/HomePage/HomeMain'
// import { userAgent } from 'next/server';
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
// import React from 'react';

// const inter = Inter({ subsets: ['latin'] })



 const Home = ()=> {
  // function Home({table}) {

  return (
    <>
      <Head> 
        <title>Crowd Funding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      </Head>
      <main >
       {/* {table.map(user => {
        return(

       
        <div key={user.id}>
         the ID no:<strong>{user.id}</strong> and NAME for id is <strong>{user.name}</strong>
        </div> 
         )
        })} */}
        <HomePage/>
     </main> 
    </>
  )
}
export default Home;
 
// export async function getServerSideProps() {
//   const res = await fetch(`https://63ef09844d5eb64db0c21d13.mockapi.io/table`);
//   const data = await res.json()


//   return {
//     props: {table:data,},
//   }
// }